# Generated by Django 3.2.20 on 2023-08-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('userid', models.DecimalField(decimal_places=0, max_digits=2)),
                ('tableid', models.DecimalField(decimal_places=0, max_digits=2)),
                ('table_name', models.CharField(max_length=20)),
                ('booked_table', models.DecimalField(decimal_places=0, max_digits=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=20)),
                ('reservt', models.DecimalField(decimal_places=0, max_digits=2)),
                ('booked_table', models.DecimalField(decimal_places=0, max_digits=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
